python mini project

introduction

in this session,the users will implement python modules,pandas,mathplotlib,seaborn,scipy and perform a mini project where certain will be assigned to the user and they must be completed.this tasks utilize the modules understanding and working.

the user will be assigned two datasets: 
1.customer information
2.loan details

using this two data sets the user has to perform this respective tasks

1.data extraction
2.data cleaning
3.data manipulation
4.data visualization(matplotlib and seaborn)
5.hypothesis testing using scipy

1.data extraction

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind

In [3]:
#read csv extract csv file
cust_data=pd.read_csv("customers_Information.csv")
loan_data=pd.read_csv("Loan_Details.csv")

In [4]:
cust_data

    customer_id    customer_name  age  credit_score       city
0           100     Aarav Sharma   40           787     Mumbai
1           102     Vihaan Mehta   65           754    Chennai
2           104      Aditya Nair   25           778    Kolkata
3           106      Rohan Verma   66           754  Bengaluru
4           108      Arjun Desai   69           602    Kolkata
5           110     Ishaan Reddy   61           669     Mumbai
6           112      Karan Gupta   61           768       Pune
7           114    Siddharth Rao   57           638     Mumbai
8           116  Nikhil Kulkarni   38           623  Bengaluru
9           118    Yash Malhotra   32           681      Noida
10          120     Aarav Sharma   22           677    Chennai
11          122      Rahul Singh   54           767  Ahmedabad
12          124     Dhruv Chawla   26           721  Bengaluru
13          126       Varun Bhat   66           769      Noida
14          128      Raghav Jain   58           767    Lucknow
15          130      Harsh Patel   39           650   Gurugram
16          132      Amit Shukla   42           652  Bengaluru
17          134      Neeraj Soni   49           643       Pune
18          136    Sandeep Yadav   26           645     Mumbai
19          138    Pranav Shetty   44           644  Bengaluru
20          140      Rohan Verma   29           613    Kolkata
21          142   Devansh Kapoor   51           616       Pune
22          144    Rakesh Mishra   30           678  Bengaluru
23          146   Abhinav Pandey   67           635       Pune
24          148    Manoj Chauhan   69           729      Noida
25          150       Sneha Iyer   48           714      Noida
26          152  Aditi Mukherjee   58           767     Mumbai
27          154  Riya Srivastava   51           603    Chennai
28          156   Neha Venkatesh   39           619      Noida
29          158         John Doe   66           790    Chennai
30          160       Sneha Iyer   60           730  Bengaluru
31          162     Ananya Sinha   23           781  Ahmedabad
32          164      Pooja Joshi   34           637       Pune
33          166   Meera Kulkarni   50           775  Ahmedabad
34          168    Shreya Bhatia   34           630      Noida
35          170      Navya Menon   56           730  Ahmedabad
36          172  Priya Deshpande   36           655    Chennai
37          174     Tanvi Pillai   45           716      Noida
38          176      Rashmi Nair   22           770     Mumbai
39          178        Divya Rao   50           623    Lucknow
40          180      Pooja Joshi   67           673     Mumbai
41          182      Swati Patel   41           683      Noida
42          184     Mahima Gupta   65           728      Noida
43          186     Sakshi Reddy   69           760    Chennai
44          188    Pallavi Verma   36           681      Noida
45          190    Jahnavi Mehta   29           697     Mumbai
46          192   Kritika Shetty   27           627   Gurugram
47          194     Rupali Singh   45           717  Ahmedabad
48          196      Chaitra Rao   59           630       Pune
49          198      Maya Sharma   67           615  Bengaluru

In [5]:
loan_data

,customer_id,application_id,loan_term,loan_type,loan_amount,approval_status,interest_rate
0,100,1,18,Home,64285.714286,Approved,12
1,102,2,3,Personal,500000.000000,Not Approved,18
2,104,3,14,Education,10000.000000,Approved,4
3,106,4,8,Business,20000.000000,Approved,6
4,108,5,7,Education,30000.000000,Under Review,17
5,110,6,35,Personal,64285.714286,Under Review,10
6,112,7,0,Education,50000.000000,Approved,13
7,114,8,33,Personal,20000.000000,Not Approved,4
8,116,9,23,Home,10000.000000,Under Review,11
9,118,10,12,Home,500000.000000,Not Approved,13
10,120,11,27,Personal,200000.000000,Approved,3
11,122,12,24,Business,30000.000000,Under Review,7
12,124,13,34,Business,10000.000000,Not Approved,6
13,126,14,31,Personal,10000.000000,Not Approved,17
14,128,15,25,Business,100000.000000,Under Review,15
15,130,16,8,Education,100000.000000,Not Approved,3
16,132,17,6,Home,100000.000000,Approved,5
17,134,18,21,Home,20000.000000,Approved,17
18,136,19,15,Home,100000.000000,Not Approved,15
19,138,20,17,Business,500000.000000,Approved,1
20,140,21,24,Personal,64285.714286,Under Review,12
21,142,22,22,Personal,10000.000000,Approved,5
22,144,23,6,Education,50000.000000,Approved,16
23,146,24,29,Home,30000.000000,Not Approved,6
24,148,25,3,Home,100000.000000,Not Approved,6
25,150,26,27,Business,10000.000000,Approved,14
26,152,27,21,Business,100000.000000,Approved,11
27,154,28,19,Home,500000.000000,Under Review,2
28,156,29,30,Business,50000.000000,Not Approved,10
29,158,30,0,Education,30000.000000,Not Approved,3
30,160,31,22,Education,20000.000000,Not Approved,6
31,162,32,1,Business,500000.000000,Not Approved,17
32,164,33,34,Home,40000.000000,Not Approved,18
33,166,34,12,Business,200000.000000,Not Approved,8
34,168,35,35,Business,40000.000000,Under Review,19
35,170,36,10,Education,50000.000000,Not Approved,6
36,172,37,26,Personal,30000.000000,Under Review,19
37,174,38,22,Business,20000.000000,Approved,14
38,176,39,24,Home,20000.000000,Under Review,5
39,178,40,14,Education,10000.000000,Under Review,7
40,180,41,21,Business,64285.714286,Under Review,8
41,182,42,11,Business,20000.000000,Under Review,10
42,184,43,27,Business,20000.000000,Under Review,1
43,186,44,10,Personal,64285.714286,Approved,13
44,188,45,35,Personal,20000.000000,Under Review,12
45,190,46,27,Personal,200000.000000,Not Approved,5
46,192,47,7,Education,50000.000000,Not Approved,14
47,194,48,14,Education,200000.000000,Not Approved,17
48,196,49,15,Business,100000.000000,Under Review,16
49,198,50,32,Home,200000.000000,Not Approved,11

2.data cleaning

In [ ]:
#1.null vales/missing,
#2.duplicate

##null vales
isnull().sum()
isnull()==1
fillna(value)

In [6]:
cust_data.isnull().sum()

customer_id      0
customer_name    0
age              0
credit_score     0
city             0
dtype: int64

In [7]:
loan_data.isnull().sum()

customer_id        0
application_id     0
loan_term          0
loan_type          0
loan_amount        0
approval_status    0
interest_rate      0
dtype: int64

Duplicates

.duplicated()     same
.duplicated()==1  same
.isin()   how many duplicate
.drop

In [10]:
cust_data[cust_data["customer_name"].duplicated()]

    customer_id customer_name  age  credit_score       city
10          120  Aarav Sharma   22           677    Chennai
20          140   Rohan Verma   29           613    Kolkata
30          160    Sneha Iyer   60           730  Bengaluru
40          180   Pooja Joshi   67           673     Mumbai

In [12]:
loan_data[loan_data["customer_id"].duplicated()]

Empty DataFrame
Columns: [customer_id, application_id, loan_term, loan_type, loan_amount, approval_status, interest_rate]
Index: []

In [13]:
cust_data[cust_data["customer_name"].isin(["Aarav Sharma","Rohan Verma","Sneha Iyer","Pooja Joshi"])]

    customer_id customer_name  age  credit_score       city
0           100  Aarav Sharma   40           787     Mumbai
3           106   Rohan Verma   66           754  Bengaluru
10          120  Aarav Sharma   22           677    Chennai
20          140   Rohan Verma   29           613    Kolkata
25          150    Sneha Iyer   48           714      Noida
30          160    Sneha Iyer   60           730  Bengaluru
32          164   Pooja Joshi   34           637       Pune
40          180   Pooja Joshi   67           673     Mumbai

In [14]:
cust_data=cust_data.drop([10,20,30,40],axis=0) #0 ->row 1 ->coloumm

In [15]:
cust_data

    customer_id    customer_name  age  credit_score       city
0           100     Aarav Sharma   40           787     Mumbai
1           102     Vihaan Mehta   65           754    Chennai
2           104      Aditya Nair   25           778    Kolkata
3           106      Rohan Verma   66           754  Bengaluru
4           108      Arjun Desai   69           602    Kolkata
5           110     Ishaan Reddy   61           669     Mumbai
6           112      Karan Gupta   61           768       Pune
7           114    Siddharth Rao   57           638     Mumbai
8           116  Nikhil Kulkarni   38           623  Bengaluru
9           118    Yash Malhotra   32           681      Noida
11          122      Rahul Singh   54           767  Ahmedabad
12          124     Dhruv Chawla   26           721  Bengaluru
13          126       Varun Bhat   66           769      Noida
14          128      Raghav Jain   58           767    Lucknow
15          130      Harsh Patel   39           650   Gurugram
16          132      Amit Shukla   42           652  Bengaluru
17          134      Neeraj Soni   49           643       Pune
18          136    Sandeep Yadav   26           645     Mumbai
19          138    Pranav Shetty   44           644  Bengaluru
21          142   Devansh Kapoor   51           616       Pune
22          144    Rakesh Mishra   30           678  Bengaluru
23          146   Abhinav Pandey   67           635       Pune
24          148    Manoj Chauhan   69           729      Noida
25          150       Sneha Iyer   48           714      Noida
26          152  Aditi Mukherjee   58           767     Mumbai
27          154  Riya Srivastava   51           603    Chennai
28          156   Neha Venkatesh   39           619      Noida
29          158         John Doe   66           790    Chennai
31          162     Ananya Sinha   23           781  Ahmedabad
32          164      Pooja Joshi   34           637       Pune
33          166   Meera Kulkarni   50           775  Ahmedabad
34          168    Shreya Bhatia   34           630      Noida
35          170      Navya Menon   56           730  Ahmedabad
36          172  Priya Deshpande   36           655    Chennai
37          174     Tanvi Pillai   45           716      Noida
38          176      Rashmi Nair   22           770     Mumbai
39          178        Divya Rao   50           623    Lucknow
41          182      Swati Patel   41           683      Noida
42          184     Mahima Gupta   65           728      Noida
43          186     Sakshi Reddy   69           760    Chennai
44          188    Pallavi Verma   36           681      Noida
45          190    Jahnavi Mehta   29           697     Mumbai
46          192   Kritika Shetty   27           627   Gurugram
47          194     Rupali Singh   45           717  Ahmedabad
48          196      Chaitra Rao   59           630       Pune
49          198      Maya Sharma   67           615  Bengaluru

In [16]:
##data manipulation

1.top 5 highest loan amounts
2.least 5 loan amounts
3.cities with most number of loan customers
4.how many are approved,not approved,under review
5.top 5 customers with hightest loan interest
6.cities and customers with sum of loan amounts and sum of interests

In [19]:
cust_data.describe()

       customer_id        age  credit_score
count    46.000000  46.000000     46.000000
mean    148.913043  47.500000    693.869565
std      29.681888  14.723753     61.587376
min     100.000000  22.000000    602.000000
25%     124.500000  36.000000    637.250000
50%     149.000000  48.500000    682.000000
75%     173.500000  60.500000    758.500000
max     198.000000  69.000000    790.000000

In [18]:
loan_data.describe()

       customer_id  application_id  loan_term    loan_amount  interest_rate
count    50.000000        50.00000  50.000000      50.000000      50.000000
mean    149.000000        25.50000  18.820000  105028.571429      10.160000
std      29.154759        14.57738  10.379906  143826.229087       5.369453
min     100.000000         1.00000   0.000000   10000.000000       1.000000
25%     124.500000        13.25000  10.250000   20000.000000       6.000000
50%     149.000000        25.50000  21.000000   50000.000000      10.500000
75%     173.500000        37.75000  27.000000  100000.000000      14.750000
max     198.000000        50.00000  35.000000  500000.000000      19.000000

In [20]:
#1.top 5 loan amounts
loan_details=pd.merge(cust_data,loan_data,on="customer_id", how ="inner")
loan_details

,customer_id,customer_name,age,credit_score,city,application_id,loan_term,loan_type,loan_amount,approval_status,interest_rate
0,100,Aarav Sharma,40,787,Mumbai,1,18,Home,64285.714286,Approved,12
1,102,Vihaan Mehta,65,754,Chennai,2,3,Personal,500000.000000,Not Approved,18
2,104,Aditya Nair,25,778,Kolkata,3,14,Education,10000.000000,Approved,4
3,106,Rohan Verma,66,754,Bengaluru,4,8,Business,20000.000000,Approved,6
4,108,Arjun Desai,69,602,Kolkata,5,7,Education,30000.000000,Under Review,17
5,110,Ishaan Reddy,61,669,Mumbai,6,35,Personal,64285.714286,Under Review,10
6,112,Karan Gupta,61,768,Pune,7,0,Education,50000.000000,Approved,13
7,114,Siddharth Rao,57,638,Mumbai,8,33,Personal,20000.000000,Not Approved,4
8,116,Nikhil Kulkarni,38,623,Bengaluru,9,23,Home,10000.000000,Under Review,11
9,118,Yash Malhotra,32,681,Noida,10,12,Home,500000.000000,Not Approved,13
10,122,Rahul Singh,54,767,Ahmedabad,12,24,Business,30000.000000,Under Review,7
11,124,Dhruv Chawla,26,721,Bengaluru,13,34,Business,10000.000000,Not Approved,6
12,126,Varun Bhat,66,769,Noida,14,31,Personal,10000.000000,Not Approved,17
13,128,Raghav Jain,58,767,Lucknow,15,25,Business,100000.000000,Under Review,15
14,130,Harsh Patel,39,650,Gurugram,16,8,Education,100000.000000,Not Approved,3
15,132,Amit Shukla,42,652,Bengaluru,17,6,Home,100000.000000,Approved,5
16,134,Neeraj Soni,49,643,Pune,18,21,Home,20000.000000,Approved,17
17,136,Sandeep Yadav,26,645,Mumbai,19,15,Home,100000.000000,Not Approved,15
18,138,Pranav Shetty,44,644,Bengaluru,20,17,Business,500000.000000,Approved,1
19,142,Devansh Kapoor,51,616,Pune,22,22,Personal,10000.000000,Approved,5
20,144,Rakesh Mishra,30,678,Bengaluru,23,6,Education,50000.000000,Approved,16
21,146,Abhinav Pandey,67,635,Pune,24,29,Home,30000.000000,Not Approved,6
22,148,Manoj Chauhan,69,729,Noida,25,3,Home,100000.000000,Not Approved,6
23,150,Sneha Iyer,48,714,Noida,26,27,Business,10000.000000,Approved,14
24,152,Aditi Mukherjee,58,767,Mumbai,27,21,Business,100000.000000,Approved,11
25,154,Riya Srivastava,51,603,Chennai,28,19,Home,500000.000000,Under Review,2
26,156,Neha Venkatesh,39,619,Noida,29,30,Business,50000.000000,Not Approved,10
27,158,John Doe,66,790,Chennai,30,0,Education,30000.000000,Not Approved,3
28,162,Ananya Sinha,23,781,Ahmedabad,32,1,Business,500000.000000,Not Approved,17
29,164,Pooja Joshi,34,637,Pune,33,34,Home,40000.000000,Not Approved,18
30,166,Meera Kulkarni,50,775,Ahmedabad,34,12,Business,200000.000000,Not Approved,8
31,168,Shreya Bhatia,34,630,Noida,35,35,Business,40000.000000,Under Review,19
32,170,Navya Menon,56,730,Ahmedabad,36,10,Education,50000.000000,Not Approved,6
33,172,Priya Deshpande,36,655,Chennai,37,26,Personal,30000.000000,Under Review,19
34,174,Tanvi Pillai,45,716,Noida,38,22,Business,20000.000000,Approved,14
35,176,Rashmi Nair,22,770,Mumbai,39,24,Home,20000.000000,Under Review,5
36,178,Divya Rao,50,623,Lucknow,40,14,Education,10000.000000,Under Review,7
37,182,Swati Patel,41,683,Noida,42,11,Business,20000.000000,Under Review,10
38,184,Mahima Gupta,65,728,Noida,43,27,Business,20000.000000,Under Review,1
39,186,Sakshi Reddy,69,760,Chennai,44,10,Personal,64285.714286,Approved,13
40,188,Pallavi Verma,36,681,Noida,45,35,Personal,20000.000000,Under Review,12
41,190,Jahnavi Mehta,29,697,Mumbai,46,27,Personal,200000.000000,Not Approved,5
42,192,Kritika Shetty,27,627,Gurugram,47,7,Education,50000.000000,Not Approved,14
43,194,Rupali Singh,45,717,Ahmedabad,48,14,Education,200000.000000,Not Approved,17
44,196,Chaitra Rao,59,630,Pune,49,15,Business,100000.000000,Under Review,16
45,198,Maya Sharma,67,615,Bengaluru,50,32,Home,200000.000000,Not Approved,11

In [24]:
#top 5 loans amount --pd.grouphy()
loan_details.groupby("customer_name")["loan_amount"].sum().sort_values(ascending=False).head(5)

customer_name
Ananya Sinha       500000.0
Pranav Shetty      500000.0
Riya Srivastava    500000.0
Vihaan Mehta       500000.0
Yash Malhotra      500000.0
Name: loan_amount, dtype: float64

In [26]:
##2.lowest
loan_details.groupby("customer_name")["loan_amount"].sum().sort_values(ascending=False).tail(5)

customer_name
Aditya Nair        10000.0
Divya Rao          10000.0
Nikhil Kulkarni    10000.0
Sneha Iyer         10000.0
Varun Bhat         10000.0
Name: loan_amount, dtype: float64

In [28]:
#3 cities with most number of loan customers
loan_details.groupby("city")["customer_name"].count().sort_values(ascending=False)

city
Noida        10
Mumbai        7
Bengaluru     7
Pune          6
Ahmedabad     5
Chennai       5
Gurugram      2
Kolkata       2
Lucknow       2
Name: customer_name, dtype: int64

In [29]:
#4 approved,not approved,under review
loan_details.groupby("approval_status")["customer_name"].count().sort_values(ascending=False)

approval_status
Not Approved    19
Under Review    14
Approved        13
Name: customer_name, dtype: int64

In [32]:
# top 5 loan intersest rate
loan_details.groupby("customer_name")["interest_rate"].sum().sort_values(ascending=False).head(5)

customer_name
Shreya Bhatia      19
Priya Deshpande    19
Pooja Joshi        18
Vihaan Mehta       18
Ananya Sinha       17
Name: interest_rate, dtype: int64

In [33]:
loan_details.pivot_table(index=["city","customer_name"], values=["loan_amount","interest_rate"],aggfunc="sum")

                           interest_rate    loan_amount
city      customer_name
Ahmedabad Ananya Sinha                17  500000.000000
          Meera Kulkarni               8  200000.000000
          Navya Menon                  6   50000.000000
          Rahul Singh                  7   30000.000000
          Rupali Singh                17  200000.000000
Bengaluru Amit Shukla                  5  100000.000000
          Dhruv Chawla                 6   10000.000000
          Maya Sharma                 11  200000.000000
          Nikhil Kulkarni             11   10000.000000
          Pranav Shetty                1  500000.000000
          Rakesh Mishra               16   50000.000000
          Rohan Verma                  6   20000.000000
Chennai   John Doe                     3   30000.000000
          Priya Deshpande             19   30000.000000
          Riya Srivastava              2  500000.000000
          Sakshi Reddy                13   64285.714286
          Vihaan Mehta                18  500000.000000
Gurugram  Harsh Patel                  3  100000.000000
          Kritika Shetty              14   50000.000000
Kolkata   Aditya Nair                  4   10000.000000
          Arjun Desai                 17   30000.000000
Lucknow   Divya Rao                    7   10000.000000
          Raghav Jain                 15  100000.000000
Mumbai    Aarav Sharma                12   64285.714286
          Aditi Mukherjee             11  100000.000000
          Ishaan Reddy                10   64285.714286
          Jahnavi Mehta                5  200000.000000
          Rashmi Nair                  5   20000.000000
          Sandeep Yadav               15  100000.000000
          Siddharth Rao                4   20000.000000
Noida     Mahima Gupta                 1   20000.000000
          Manoj Chauhan                6  100000.000000
          Neha Venkatesh              10   50000.000000
          Pallavi Verma               12   20000.000000
          Shreya Bhatia               19   40000.000000
          Sneha Iyer                  14   10000.000000
          Swati Patel                 10   20000.000000
          Tanvi Pillai                14   20000.000000
          Varun Bhat                  17   10000.000000
          Yash Malhotra               13  500000.000000
Pune      Abhinav Pandey               6   30000.000000
          Chaitra Rao                 16  100000.000000
          Devansh Kapoor               5   10000.000000
          Karan Gupta                 13   50000.000000
          Neeraj Soni                 17   20000.000000
          Pooja Joshi                 18   40000.000000